services:
  db:
    image: postgres:13
    container_name: wellness_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wellness_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile
    container_name: wellness_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/wellness_ai?schema=public

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: wellness_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

volumes:
  postgres_data: